version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8001
      - PORT=3001
      - WDS_SOCKET_PORT=3001
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge