version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
    networks:
      appnet:
        aliases:
          - backend
          - api

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/build:/frontend_build
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REACT_APP_API_URL=http://88.218.67.17:8001 # заменить
    depends_on:
      - backend
    networks:
      appnet:
        aliases:
          - frontend
          - web

networks:
  appnet:
    name: app_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    driver_opts:
      com.docker.network.bridge.name: app_network
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"