name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  backend-build:
    runs-on: ubuntu-latest
    name: Build Backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      working-directory: ./backend
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi

    - name: Run backend tests
      working-directory: ./backend
      run: |
        poetry run pytest

    - name: Build backend Docker image
      run: |
        docker build -t backend:latest -f ./backend/Dockerfile ./backend

  frontend-build:
    runs-on: ubuntu-latest
    name: Build Frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build frontend Docker image
      run: |
        docker build -t frontend:latest -f ./frontend/Dockerfile ./frontend

  deploy:
    needs: [backend-build, frontend-build]
    runs-on: ubuntu-latest
    name: Deploy Locally

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run Docker Compose
      run: |
        docker-compose up -d